### ISSUE TITLE
Unable to link with SFML on windows

### ISSUE THREAD

**Issue by ghost** [Ticki/rugra#4]
Forgive me if I'm just being stupid, but I can't find a way to link with SFML libs on windows. Is there a way to do this?

**Comment by ticki** [comment]
Have you installed CSFML?

**Comment by ticki** [comment]
http://www.sfml-dev.org/download/csfml/

**Comment by ghost** [comment]
I'm sorry, what's the proper way to install the library? Is there a certain place I'm supposed to put the dll files?

**Comment by ticki** [comment]
Unfortunately, I cannot tell you, since I'm not a Windows user. However, I know CSFML supports Window, since multiple games for Windows are using it.

Is there a package manager for Windows? Also, can you install it via Cygwin?

**Comment by ghost** [comment]
I have the headers and the compiled library files, I just don't know how to get them to link with the build process. There's no way to install them, the *.dll files are just provided as-is.

**Comment by ghost** [comment]
I figured it out. You need a build script in order for it to work. Thanks for the help!

**Comment by ticki** [comment]
Cool.
